return [[
This block changes your custom skill's display in your hotbar.

<b><font color='rgb(221,155,155)'>Display Name</font></b>
If checked, this will change what your custom skill displays as in your hotbar.

<b><font color='rgb(221,155,155)'>Tool Tip</font></b>
If checked, this will change what your custom skill's tool tip is in your hotbar.

<b><font color='rgb(221,155,155)'>Flash Color</font></b>
If checked, will apply a colored flash animation to your custom skill in your hotbar.
]]