return [[
This block will spawn visual effects on your character.

<b><font color='rgb(221,155,155)'>Effect List</font></b>
This is a list of of all the visual effects you can use. Click any one to choose.
You quickly test an effect by <b>right-clicking</b> (or dual tapping) an effect in the list, it will emit with your given properties and coordinates.

<b><font color='rgb(221,155,155)'>Tint</font></b>
Controls the color of the visual effects when checked.

<b><font color='rgb(221,155,155)'>Scale</font></b>
Controls the overall size of the visual effects.

<b><font color='rgb(221,155,155)'>Volume</font></b>
Controls how loud the audio made (if any) by the visual effects.

<b><font color='rgb(221,155,155)'>Density</font></b>
Controls how much particles are emitted by the visual effects.

<b><font color='rgb(221,155,155)'>Position</font></b>
Controls the relative offset from your player character for where the visual effects are emit from.

<b><font color='rgb(221,155,155)'>Orientation</font></b>
Controls the relative rotation from your player character for where the visual effects are emit from.
The axes are represented in <b>degrees</b>.

<b><font color='rgb(221,155,155)'>Targeting</font></b>
Controls the target that the effect is applied to. If this block isn't accessed by a retargeting feature like 'Hit Branch To' of the skill block, there will be no target and this will do nothing.
]]