return {
	["Forward Dash"] = {RaycastDistance = 5, Messy = false, Spacing = 2.5},
	["Backward Dash"] = {RaycastDistance = 5, Messy = false, Spacing = 2.5},
	["Side Dash"] = {RaycastDistance = 5, Messy = true, Spacing = 2.5},
	
	["Flowing Hands"] = {RaycastDistance = 5, Messy = true, Spacing = 1.5},
	["Blue Pull"] = {RaycastDistance = 5, Messy = true, Spacing = 3.5},
	
	["Dragged"] = {RaycastDistance = 5, Messy = true, Spacing = 2},
	
	["Gojo Max Blue"] = {RaycastDistance = 7.5, Messy = true, Spacing = 12.5},
	
	["SweepFinisherRun"] = {RaycastDistance = 5, Messy = false, Spacing = 1.5},
	
	["CharaLethalWoundSlide"] = {RaycastDistance = 7.5, Messy = true, Spacing = 1.75, Size = 0.85, FadeInTime = 0.05},
	
	["CarnalRevolution"] = {RaycastDistance = 15, Messy = true, Spacing = 10, Size = 1.55},
	
	["Purple"] = {RaycastDistance = 15, Messy = false, Spacing = 12, Size = 2.5},
}