local MultipleChoiceList = {}

MultipleChoiceList.List = {
	["Dummy Type"] = {
		Title = "Dummy Type",
		
		Choices = {
			"Regular Dummy",
			"M1ing Dummy",
			"Blocking Dummy",
			"Low HP Dummy",
			"Atonement Dummy",
			"Emoting Dummy",
			--"Green Blob Dummy",
			--"The Strongest Dummy",
			"Sweep Dummy",
			--"Tectonic Control Dummy",
			--"Palm Strikes Dummy",
			--"Draupnir Spin Dummy",
			--"Starflare Dummy"
			--"Leviathan Throw Dummy"
		}
	}
}

return MultipleChoiceList
