local Gamepasses = {
	["Early Access"] = {
		Order = 1,
		Description = "Gain access to use unreleased characters", 
		Price = "299", 
		GiftID = 2672893075, 
		ID = 920797302,
	},
	
	["Extra Emote Slots"] = {
		Order = 2,
		Description = "Increases Emote Slots from 4 -> 8", 
		Price = "100", 
		GiftID = 3257117601, 
		ID = 966942108,
	},
	
	["Private Server+"] = {
		Order = 3,
		Description = "Grants you access to more PS Commands", 
		Price = "499", 
		GiftID = 3257118162, 
		ID = 1040382354,
	},
	
	["Kill Sounds"] = {
		Order = 4,
		Description = "Play a Custom Sound after killing a player", 
		Price = "100", 
		GiftID = 3257118626, 
		ID = 1039898973,
	},
}

return Gamepasses