return {
	{
		Title = "Logical",
		SubTitle = "Has control modifiers";
		Layout = 2;
	},
	{
		Title = "Misc";
		SubTitle = "Has miscellaneous modifiers";
		Layout = 5;
	};
	{
		Title = "Gameplay";
		SubTitle = "Has modifiers related to gameplay";
		Layout = 4;
	};
	{
		Title = "Advanced";
		SubTitle = "Has advanced behaviour modifiers";
		Layout = 7;
	};
	{
		Title = "Purchased";
		SubTitle = "Has your purchased modifiers";
		Layout = 0;
	};
	{
		Title = "Splitting";
		SubTitle = "Has modifiers based on IDs";
		Layout = 7;
	};
	{
		Title = "Gates";
		SubTitle = "Has logic gates";
		Layout = 3;
	};
	{
		Title = "Sensors";
		SubTitle = "Has sensors that detect world phenomena";
		Layout = 1;
	};
	{
		Title = "Points";
		SubTitle = "Has modifiers that can check and give leaderboard stats.";
		Layout = 6;
	};
};