return {
	["Combat Gods + Isagi"] = os.time({ -- april 29, make sure to edit this if we're putting it back on sale
		year = 2025,
		month = 4,
		day = 29, 
		hour = 0,
		min = 0,
		sec = 0
	}),
	
	["Love Train"] = os.time({ -- june 2
		year = 2025,
		month = 6,
		day = 2, 
		hour = 0,
		min = 0,
		sec = 0
	}),
	
	["Final Matchup"] = os.time({ -- aug 10
		year = 2025,
		month = 8,
		day = 10, 
		hour = 0,
		min = 0,
		sec = 0
	}),
	
	["The Final Showdown"] = os.time({ -- sept 28
		year = 2025,
		month = 9,
		day = 28, 
		hour = 0,
		min = 0,
		sec = 0
	})
}