return {
	["Soft Blue"] = {StartTransparency = 0.5, Color = Color3.fromRGB(20, 102, 255)},
	
	["Black Flash"] = {StartTransparency = 0.5, Color = Color3.fromRGB(255, 0, 0)},
	["Blue Choose"] = {StartTransparency = 0.5, Color = Color3.fromRGB(20, 102, 255)},
	
	["Regeneration"] = {StartTransparency = 0.8, Color = Color3.fromRGB(0, 255, 0)},
	
	["Bio Electric Burst Hit"] = {StartTransparency = 0.825, Color = Color3.fromRGB(141, 60, 255)},
	["Bio Electric Burst Final Hit"] = {StartTransparency = 0.5, Color = Color3.fromRGB(141, 60, 255)},
	["Vector Punch"] = {StartTransparency = 0.15, Color = Color3.fromRGB(141, 60, 255), FadeTime = 2},
	
	["Lightning"] = {StartTransparency = 0.75, Color = Color3.fromRGB(158, 208, 255)},
	
	["Plasmic Degree"] = {StartTransparency = 0.5, Color = Color3.fromRGB(120, 110, 255)},
	["Plasmic Degree Explosion"] = {StartTransparency = 0.1, Color = Color3.fromRGB(120, 110, 255)},
	
	["Gojo Ultimate Shine"] = {StartTransparency = 0.35, Color = Color3.fromRGB(254, 205, 92)},
}