local ServerScriptService = game:GetService("ServerScriptService")
local ServerStorage = game:GetService("ServerStorage")
local BaseAttack = require( ServerStorage.serverCombat.Attacks.BaseAttack )

return {
	Template = nil;
	Object = nil,
	
	--Equipped = function(self)
	
	--end,
	
	--Unequipped = function(self)
	
	--end,
	
	--OnSpawn = function(self, Tool)
		
	--end,
	
	--OnPickedUp = function(self, Item)
		
	--end,
	
	--Triggered = function(self)
		
	--end,
}