return [[
This block will animate the target character with an animation thats available in-game.
The block will show you a preview of your chosen animation, you can edit the timing of what part of the animation should be played by using the two timeline start and end pointers on the blue bar below.

<b><font color='rgb(221,155,155)'>Animation List</font></b>
This is a list of of all the animations you can use. Click any one to choose, and they will appear in your preview timeline.

<b><font color='rgb(221,155,155)'>Speed</font></b>
Controls the how fast the animation should be played.

<b><font color='rgb(221,155,155)'>Scale</font></b>
Controls whether the animation should loop. If you make your animation looped, the animation will always stop when your custom skill ends (to prevent a permenant, playing animation).

<b><font color='rgb(221,155,155)'>Cancellable</font></b>
Controls whether the animation will stop if your custom skill gets cancelled.

<b><font color='rgb(221,155,155)'>Overwrite Previous</font></b>
If checked, this will stop <b>all</b> previous playing animations. Use a <i>Cancel</i> block if you want to cancel a particular Animation block instead.

<b><font color='rgb(221,155,155)'>Targeting</font></b>
Controls the target that the effect is applied to. If this block isn't accessed by a retargeting feature like 'Hit Branch To' of the skill block, there will be no target and this will do nothing.
]]