return {
	["Camera_Shake"] = 100,
	["Ultimate_Music"] = 100,
	["Sound_Effects"] = 100,
	["Environment"] = 100,
	["Emotes"] = 100,
	["Kill_Sounds"] = 100,
	["UI"] = 100,
	
	["Gamepad_Sensitivity"] = 100,
	
	--["M1_Hitbox_Compensate"] = true,
	--["Dash_Hitbox_Compensate"] = true,
	
	["Epileptic_Mode"] = false,
	["Blood"] = false,
	["Cutscenes"] = true,
	["Dialogue"] = true,
	["Rain"] = true,
	["Foliage_Wind"] = true,
	["Evasive_IFrame_Highlight"] = true,
	["Hit_IFrame_Effect"] = true,
	["Tile_Destruction"] = true,
	["Tile_Split_Geometry"] = true,
	["Accessories"] = true,
	["Voxel_Interpolation"] = true,
	["Head_Tracking"] = true,
	["HUD_Sway"] = true,
	["Auto_Use"] = true,
	["Kill_Sound"] = "0",
	
	["Red_Mist_Avatar"] = true,
} 