return [[
This block can cancel a subset blocks that are active within your custom skill.

<b><font color='rgb(221,155,155)'>To Previous</font></b>
If checked, Controls what block should be cancelled in particular (starting from this block, is how many steps back the block you want cancelled should be)
If this is unchecked, then <b>all</b> previous blocks will be cancelled.

<b><font color='rgb(221,155,155)'>Include Up To Previous</font></b>
Controls whether <i>To Previous</i> will include every block up until to be cancelled.

<b><font color='rgb(221,155,155)'>Ignore Cancellable</font></b>
Controls whether the this block will ignore the <i>Cancellable</i> property on the affected block (if it has one).

<b><font color='rgb(221,155,155)'>Current Branch Only</font></b>
Controls whether this cancel block can backtrack to other branches.

<b><font color='rgb(221,155,155)'>Skill</font></b>
Whether <b>Skill</b> blocks should be affected.

<b><font color='rgb(221,155,155)'>Sound</font></b>
Whether <b>Sound</b> blocks should be affected.

<b><font color='rgb(221,155,155)'>Velocity</font></b>
Whether <b>Velocity</b> blocks should be affected.

<b><font color='rgb(221,155,155)'>Animation</font></b>
Whether <b>Animation</b> blocks should be affected.
]]